dist: trusty
language: java

services: mongodb

jdk:
  - oraclejdk8

before_script:
  - sleep 15
  - mongo localhost:27017/local ./scripts/Script_Jugadores.js 

script:
  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install jacoco:report coveralls:report

